---

- name: Ensure logrotate package is present
  ansible.builtin.package:
    name: logrotate
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Add logrotate configuration for starbase logs
  ansible.builtin.template:
    src: logrotate-starbase.j2
    dest: /etc/logrotate.d/starbase
    mode: '0644'
    validate: 'logrotate -dv %s'
    backup: yes
